name: Upload latest to DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ master, ]

jobs:
  docker:

    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DuckerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          platforms: linux/amd64
          push: true
          tags: dmd3eorg/mercure-munge-tags:latest
            